---
variables:
  VERSION: "v1.0"

stages:
    - check_bugfix
    - check_develop
    - check_prod

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request, schedules & triggered)
Bugfix:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_bugfix
    only:
      refs:
        - merge_requests
        - schedules
      variables:
        - $RELEASE == "bugfix"
    <<: *tmpl_check

Develop:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_develop
    only:
      refs:
        - schedules
      variables:
        - $RELEASE == "develop"
    <<: *tmpl_check

Prod:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_prod
    only:
      refs:
        - merge_requests
        - schedules
        - triggers
      variables:
        - $RELEASE == "prod"
    <<: *tmpl_check
