---
stages:
    - scheduled_check_develop
    - scheduled_check_bugfix
    - scheduled_check_master
    - check_bugfix_before_merge
    - check_master_after_merge

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${REGISTRY_IMAGES}
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check scheduled - BoF
Scheduled Bugfix:
    stage: scheduled_check_bugfix
    only:
      refs:
        - schedules
        - bugfix
      variables:
        - $RELEASE == "bugfix"
    <<: *tmpl_check

Scheduled Develop:
    stage: scheduled_check_develop
    only:
      refs:
        - schedules
        - v99.99
      variables:
        - $RELEASE == "develop"
    <<: *tmpl_check

Scheduled Prod:
    stage: scheduled_check_master
    only:
      refs:
        - schedules
        - v7.0
      variables:
        - $RELEASE == "prod"
    <<: *tmpl_check
# #### Project check scheduled - EoF

# #### Project check merge request - BoF
Bugfix:
    stage: check_bugfix_before_merge
    only:
      refs:
        - merge_requests
    <<: *tmpl_check

Prod:
    stage: check_master_after_merge
    <<: *tmpl_check
    only:
        - v7.0
    except:
        - schedules
    when: on_success
# #### Project check merge request - EoF
