---
stages:
    - check_bugfix
    - check_develop
    - check_prod

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${REGISTRY_IMAGES}
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request, schedules & triggered)
Develop:
    stage: check_develop
    only:
      refs:
        - schedules
      variables:
        - $RELEASE == "develop"
    <<: *tmpl_check

Bugfix:
    stage: check_bugfix
    only:
      refs:
        - merge_requests
        - schedules
      variables:
        - $RELEASE == "bugfix"
    <<: *tmpl_check

Prod:
    stage: check_prod
    only:
      refs:
        - merge_requests
        - schedules
        - triggers
      variables:
        - $RELEASE == "bugfix"
        - $RELEASE == "prod"
    when: on_success
    <<: *tmpl_check
